---
- name: Create the home dir
  ansible.builtin.file:
    path: "{{ item.mount_point }}/{{ home_dir }}"
    state: directory
    mode: '0755'
    
- name: Show mount results
  ansible.builtin.debug:
    msg: "Home directory created {{ item.mount_point }}/{{ home_dir }}"



ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5WX0tlEa26ISUK2XaOHej5VCCLzV98MIvF0yANnAzn1uDktDEfvNRcGm52kEM1dl0OJ4yeGePQcT7mYnS45LKRINz1SGCYgzqJ81OfzLmNBC2wy9Sn9kOsGzBd+NTdlWPv73PK9fcEOnER7Ghs08Ttk98HcTOMLfi3svYVKTJTDgrCY/D+JQ4Jr+RyECexSS4cQgHB6sEEhpnBG1ajYFsk38yFnl1zEyj0dVEyxk2uFm5CB6sXo+w38B2TixlyHl5D78I6RtULLgpRGBEoxkOvQp5ZkvjbWmkqD+nr1v0/DfviLd3RZnwYTe4dtXcsQfS6XR8ImkyMLXZqyW01FCWABlZbraORnTrRH+r9kOFgcNtgCi527bkdWjsxd89HDv3evi9zAdU5Hv9Un0FR5aYS2SVB1uKJTP58fRMStyeMEoPMWrzRmaJj2ZdPSi5319dZEFk1ggvJVMfkny4gqiJHOEh5YEmgUah5uNhUDSn+JA5wAUBkDLOqCYaEnve4Auu4N7SfkPTKp3BAzxgc0D+y/hOrIj3OgG7xKB1U9iAtyE3uLa9EN3I1RD0EOr85aKY+0iHAtCAZ4ntd8XcOpwVRRe/vnPBeY/VAst5WWFPxO97PXLugEnhh12eeuLKlYgpJd3AC9FAZPORiHPMxVQW48zeb/Z7hF+fPYjYVmsKdw== kailumalshete@gmail.com
